// Copyright (c) DGP Studio. All rights reserved.
// Licensed under the MIT license.

namespace Snap.Hutao.Win32.System.LibraryLoader;

[Flags]
internal enum LOAD_LIBRARY_FLAGS : uint
{
    DONT_RESOLVE_DLL_REFERENCES = 1u,
    LOAD_LIBRARY_AS_DATAFILE = 2u,
    LOAD_WITH_ALTERED_SEARCH_PATH = 8u,
    LOAD_IGNORE_CODE_AUTHZ_LEVEL = 0x10u,
    LOAD_LIBRARY_AS_IMAGE_RESOURCE = 0x20u,
    LOAD_LIBRARY_AS_DATAFILE_EXCLUSIVE = 0x40u,
    LOAD_LIBRARY_REQUIRE_SIGNED_TARGET = 0x80u,
    LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR = 0x100u,
    LOAD_LIBRARY_SEARCH_APPLICATION_DIR = 0x200u,
    LOAD_LIBRARY_SEARCH_USER_DIRS = 0x400u,
    LOAD_LIBRARY_SEARCH_SYSTEM32 = 0x800u,
    LOAD_LIBRARY_SEARCH_DEFAULT_DIRS = 0x1000u,
    LOAD_LIBRARY_SAFE_CURRENT_DIRS = 0x2000u,
    LOAD_LIBRARY_SEARCH_SYSTEM32_NO_FORWARDER = 0x4000u
}
