// Copyright (c) DGP Studio. All rights reserved.
// Licensed under the MIT license.

namespace Snap.Hutao.Win32.UI.Shell.PropertiesSystem;

[Flags]
internal enum GETPROPERTYSTOREFLAGS
{
    GPS_DEFAULT = 0,
    GPS_HANDLERPROPERTIESONLY = 1,
    GPS_READWRITE = 2,
    GPS_TEMPORARY = 4,
    GPS_FASTPROPERTIESONLY = 8,
    GPS_OPENSLOWITEM = 0x10,
    GPS_DELAYCREATION = 0x20,
    GPS_BESTEFFORT = 0x40,
    GPS_NO_OPLOCK = 0x80,
    GPS_PREFERQUERYPROPERTIES = 0x100,
    GPS_EXTRINSICPROPERTIES = 0x200,
    GPS_EXTRINSICPROPERTIESONLY = 0x400,
    GPS_VOLATILEPROPERTIES = 0x800,
    GPS_VOLATILEPROPERTIESONLY = 0x1000,
    GPS_MASK_VALID = 0x1FFF,
}