files:
  - source: /src/Snap.Hutao/Snap.Hutao/Resource/Localization/SH.resx
    translation: /src/Snap.Hutao/Snap.Hutao/Resource/Localization/SH.%osx_locale%.resx
  - source: /src/Snap.Hutao/Snap.Hutao/Resource/Localization/SHRegex.resx
    translation: /src/Snap.Hutao/Snap.Hutao/Resource/Localization/SHRegex.%osx_locale%.resx