// Copyright (c) DGP Studio. All rights reserved.
// Licensed under the MIT license.

namespace Snap.Hutao.Model.Intrinsic;

/// <summary>
/// 材料类型
/// </summary>
internal enum MaterialType
{
    MATERIAL_NONE = 0,
    MATERIAL_FOOD = 1,
    MATERIAL_QUEST = 2,

    MATERIAL_EXCHANGE = 4,
    MATERIAL_CONSUME = 5,
    MATERIAL_EXP_FRUIT = 6,
    MATERIAL_AVATAR = 7,
    MATERIAL_ADSORBATE = 8,
    MATERIAL_CRICKET = 9,
    MATERIAL_ELEM_CRYSTAL = 10,
    MATERIAL_WEAPON_EXP_STONE = 11,
    MATERIAL_CHEST = 12,
    MATERIAL_RELIQUARY_MATERIAL = 13,
    MATERIAL_AVATAR_MATERIAL = 14,
    MATERIAL_NOTICE_ADD_HP = 15,
    MATERIAL_SEA_LAMP = 16,
    MATERIAL_SELECTABLE_CHEST = 17,
    MATERIAL_FLYCLOAK = 18,
    MATERIAL_NAMECARD = 19,
    MATERIAL_TALENT = 20,
    MATERIAL_WIDGET = 21,
    MATERIAL_CHEST_BATCH_USE = 22,
    MATERIAL_FAKE_ABSORBATE = 23,
    MATERIAL_CONSUME_BATCH_USE = 24,
    MATERIAL_WOOD = 25,

    MATERIAL_FURNITURE_FORMULA = 27,
    MATERIAL_CHANNELLER_SLAB_BUFF = 28,
    MATERIAL_FURNITURE_SUITE_FORMULA = 29,
    MATERIAL_COSTUME = 30,
    MATERIAL_HOME_SEED = 31,
    MATERIAL_FISH_BAIT = 32,
    MATERIAL_FISH_ROD = 33,
    MATERIAL_SUMO_BUFF = 34, // sumo 活动道具，never appear
    MATERIAL_FIREWORKS = 35,
    MATERIAL_BGM = 36,
    MATERIAL_SPICE_FOOD = 37,
    MATERIAL_ACTIVITY_ROBOT = 38,
    MATERIAL_ACTIVITY_GEAR = 39,
    MATERIAL_ACTIVITY_JIGSAW = 40,
    MATERIAL_ARANARA = 41,
    MATERIAL_GCG_CARD = 42,
    MATERIAL_GCG_CARD_FACE = 43, // 影幻卡面
    MATERIAL_GCG_CARD_BACK = 44,
    MATERIAL_GCG_FIELD = 45,
    MATERIAL_DESHRET_MANUAL = 46,
    MATERIAL_RENAME_ITEM = 47,
    MATERIAL_GCG_EXCHANGE_ITEM = 48,
    MATERIAL_QUEST_EVENT_BOOK = 49,
    MATERIAL_PROFILE_PICTURE = 50,
}