// Copyright (c) DGP Studio. All rights reserved.
// Licensed under the MIT license.

namespace Snap.Hutao.Web;

// ReSharper disable InconsistentNaming
internal enum NetworkError
{
    ERR_CONNECTION_ACCESS_DENIED,
    ERR_CONNECTION_REFUSED,
    ERR_CONNECTION_NETWORK_UNREACHABLE,
    ERR_CONNECTION_TIMED_OUT,
    ERROR_NAME_RESOLUTION_HOST_NOT_FOUND,
    ERR_SECURE_CONNECTION_ABORTED,
    ERR_SECURE_CONNECTION_ERROR,
    ERR_SECURE_CONNECTION_REMOTE_CERTIFICATE_NAME_MISMATCH,
    ERR_SECURE_CONNECTION_RESET,
    OK,
}