// Copyright (c) DGP Studio. All rights reserved.
// Licensed under the MIT license.

namespace Snap.Hutao.Web;

// ReSharper disable InconsistentNaming
internal enum NetworkError
{
    ERR_CONNECTION_ABORTED,
    ERR_CONNECTION_ACCESS_DENIED,
    ERR_CONNECTION_REFUSED,
    ERR_CONNECTION_NETWORK_UNREACHABLE,
    ERR_CONNECTION_NO_DATA,
    ERR_CONNECTION_TIMED_OUT,
    ERR_NAME_RESOLUTION_HOST_NOT_FOUND,
    ERR_PROXY_TUNNEL_ERROR,
    ERR_RESPONSE_ENDED,
    ERR_SECURE_CONNECTION_ABORTED,
    ERR_SECURE_CONNECTION_AUTHENTICATION_ERROR,
    ERR_SECURE_CONNECTION_ERROR,
    ERR_SECURE_CONNECTION_RESET,
    ERR_UNKNOWN_CONNECTION_ABORTED,
    ERR_UNKNOWN_CONNECTION_RESET,
    OK,
}