name: BUG Report [English Form]
description: Tell us what issue you get
title: "[ENG][Bug]: Place your Issue Title Here"
labels: ["BUG"]
body:
  - type: markdown
    attributes:
      value: |
        > **Please use one sentence to briefly describe your issue as title above**
        > Please follow the instruction below to fill the form, so we can locate the issue quickly

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |-
        Please complete the checklist, otherwise your issue may be ignored
      options:
        - label: I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
          required: true
          
        - label: I and tried **search feature** in Snap Hutao document site, and no associated article
          required: true

        - label: My issue is not a [fixed issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D), and it's not a duplicated issue
          required: true

  - type: input
    id: winver
    attributes:
      label: Windows Version
      description: | 
        Use `Win+R` and input `winver`, Windows build version is usually at the second line
      placeholder: e.g. 22000.556
    validations:
      required: true
   
  - type: input
    id: shver
    attributes:
      label: Snap Hutao Version
      description: You can find the version in application's title bar
      placeholder: e.g. 1.4.15.0
    validations:
      required: true

  - type: input
    id: deviceid
    attributes:
      label: Device ID
      description: | 
        In Snap Hutao's settings page, you can find and copy your device ID
        If your issue is about program crash, please fill this so we can dump the log and locate the source easier 
    validations:
      required: false

  - type: dropdown
    id: user-set-category
    attributes:
      label: Issue Category
      description: Please select the most associated category of your issue
      options:
        - Installation and Environment
        - Achievement
        - My Character
        - Game Launcher
        - Realtime Note
        - Develop Plan
        - File Cache
        - Wish Export
        - Game Record
        - Hutao Database
        - User Interface
        - Snap Hutao Cloud
        - Snap Hutao Account
        - Checkin        
        - Wiki
        - Announcement
        - Other
    validations:
      required: true   

  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: Describe your issue in detail to help us identify the issue. **If your issue is about program crash, you should check Windows Event Viewer, and attach associated `.Net Error` details here**
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: What is expected?
      description: Describe expected outcome, highlight the difference with current outcome
    validations:
      required: false

  - type: checkboxes
    id: checklist-final
    attributes:
      label: Last Step
      description: Review your Form
      options:
        - label: I believe the description above is detail enough to allow developers to reproduce the issue
          required: true
      
