name: BUG Report 问题反馈
description: 告诉我们你的问题
title: "[Bug]: 在这里填写一个合适的标题"
labels: ["BUG"]
body:
  - type: markdown
    attributes:
      value: |
        > **请在上方设置一个合适的工单标题**
        > 请按下方的要求填写完整的问题表单，以便我们更快的定位问题。

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: |-
        请确保你已完整执行检查清单，否则你的 Issue 可能会被忽略
      options:
        - label: 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
          
        - label: 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词

        - label: 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)

        - label: 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
         
        - label: 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

  - type: input
    id: winver
    attributes:
      label: Windows 版本
      description: | 
        `Win+R` 输入 `winver` 回车后在打开的窗口第二行可以找到
      placeholder: 例：22621.1105
    validations:
      required: true
   
  - type: input
    id: shver
    attributes:
      label: Snap Hutao 版本
      description: 在应用标题，应用程序的设置界面中靠下的位置可以找到
      placeholder: 例：1.4.15.0
    validations:
      required: true

  - type: input
    id: deviceid
    attributes:
      label: 设备 ID
      description: | 
        在胡桃工具箱的设置界面，你可以找到并复制你的设备 ID
        如果你的问题涉及程序崩溃，请填写该项，这将有助于我们定位问题
    validations:
      required: false

  - type: dropdown
    id: user-set-category
    attributes:
      label: 问题分类
      description: 请设置一个你认为合适的分类，这将帮助我们快速定位问题
      options:
        - 安装和环境
        - 成就管理
        - 角色信息面板
        - 游戏启动器
        - 实时便笺
        - 养成计算器
        - 用户面板
        - 文件缓存
        - 祈愿记录
        - 玩家查询
        - 胡桃数据库
        - 用户界面
        - 签到
        - Wiki
        - 公告
        - 其它
    validations:
      required: true   

  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 详细的描述问题发生前后的行为，以便我们解决问题
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: 你期望发生的行为？
      description: 详细的描述你期望发生的行为，突出与目前（可能不正确的）行为的不同
    validations:
      required: false
      
