name: 功能请求 
description: 通过这个议题来向开发团队分享你的想法
title: "[Feat]: 在这里填写一个合适的标题"
labels: ["功能", "needs-triage", "priority:none"]
assignees:
  - Lightczx
body:
  - type: markdown
    attributes:
      value: |
        请按下方的要求填写完整的问题表单。

  - type: textarea
    id: back
    attributes:
      label: 背景与动机
      description: 添加此功能的理由，如果你想要实现多个功能，请分别发起多个单独的议题
    validations:
      required: true

  - type: textarea
    id: req
    attributes:
      label: 想要实现或优化的功能
      description: 详细的描述一下你想要的功能，描述的越具体，采纳的可能性越高
    validations:
      required: true