name: Publish Process
description: FOR ADMIN USE ONLY. WILL CAUSE A BAN IF NO PERMISSION.
title: "[Publish]: Version 1.9.98"
labels: ["Publish"]
assignees:
  - Lightczx
body:
- type: textarea
  id: main-body
  attributes:
    label: Publish Process
    value: |

      ## 创建版本

      - [ ]  同步一次 [Crowdin](https://crowdin.com/project/snap-hutao) 翻译
      - [ ]  发布 RC 版本（Optional）
      - [ ]  合并入主分支
      - [ ]  整理更新内容，等待翻译
      - [ ]  在 [Snap.Hutao.Docs@next-patch](https://github.com/DGP-Studio/Snap.Hutao.Docs/tree/next-patch) 分支更新文档并直接开 PR
          - [ ]  更新日志
          - [ ]  功能文档更新
          
- type: checkboxes
  id: checklist-final
  attributes:
    label: Final Check
    description: Understand what you are doing
    options:
      - label: I understand that I will get banned from repository if I don't have permission to use this template
        required: true
