// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SophonPatchManifestProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto {

  /// <summary>Holder for reflection information generated from SophonPatchManifestProto.proto</summary>
  public static partial class SophonPatchManifestProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for SophonPatchManifestProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SophonPatchManifestProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5Tb3Bob25QYXRjaE1hbmlmZXN0UHJvdG8ucHJvdG8SLlNuYXAuSHV0YW8u",
            "V2ViLkhveW9sYWIuVGFrdW1pLkRvd25sb2FkZXIuUHJvdG8iugEKDVBhdGNo",
            "TWFuaWZlc3QSSwoJRmlsZURhdGFzGAEgAygLMjguU25hcC5IdXRhby5XZWIu",
            "SG95b2xhYi5UYWt1bWkuRG93bmxvYWRlci5Qcm90by5GaWxlRGF0YRJcChJE",
            "ZWxldGVGaWxlc0VudHJpZXMYAiADKAsyQC5TbmFwLkh1dGFvLldlYi5Ib3lv",
            "bGFiLlRha3VtaS5Eb3dubG9hZGVyLlByb3RvLkRlbGV0ZUZpbGVzRW50cnki",
            "lgEKCEZpbGVEYXRhEhAKCEZpbGVOYW1lGAEgASgJEhAKCEZpbGVTaXplGAIg",
            "ASgDEhAKCEZpbGVIYXNoGAMgASgJElQKDlBhdGNoZXNFbnRyaWVzGAQgAygL",
            "MjwuU25hcC5IdXRhby5XZWIuSG95b2xhYi5UYWt1bWkuRG93bmxvYWRlci5Q",
            "cm90by5QYXRjaGVzRW50cnkiaQoMUGF0Y2hlc0VudHJ5EgsKA0tleRgBIAEo",
            "CRJMCglQYXRjaEluZm8YAiABKAsyOS5TbmFwLkh1dGFvLldlYi5Ib3lvbGFi",
            "LlRha3VtaS5Eb3dubG9hZGVyLlByb3RvLlBhdGNoSW5mbyLiAQoJUGF0Y2hJ",
            "bmZvEgoKAklkGAEgASgJEgsKA1RhZxgCIAEoCRIPCgdCdWlsZElkGAMgASgJ",
            "EhUKDVBhdGNoRmlsZVNpemUYBCABKAMSFwoPUGF0Y2hlc0ZpbGVIYXNoGAUg",
            "ASgJEhgKEFBhdGNoU3RhcnRPZmZzZXQYBiABKAMSEwoLUGF0Y2hMZW5ndGgY",
            "ByABKAMSGAoQT3JpZ2luYWxGaWxlTmFtZRgIIAEoCRIYChBPcmlnaW5hbEZp",
            "bGVTaXplGAkgASgDEhgKEE9yaWdpbmFsRmlsZUhhc2gYCiABKAkicQoQRGVs",
            "ZXRlRmlsZXNFbnRyeRILCgNLZXkYASABKAkSUAoLRGVsZXRlRmlsZXMYAiAB",
            "KAsyOy5TbmFwLkh1dGFvLldlYi5Ib3lvbGFiLlRha3VtaS5Eb3dubG9hZGVy",
            "LlByb3RvLkRlbGV0ZUZpbGVzIlYKC0RlbGV0ZUZpbGVzEkcKBUluZm9zGAEg",
            "AygLMjguU25hcC5IdXRhby5XZWIuSG95b2xhYi5UYWt1bWkuRG93bmxvYWRl",
            "ci5Qcm90by5GaWxlSW5mbyI0CghGaWxlSW5mbxIMCgROYW1lGAEgASgJEgwK",
            "BFNpemUYAiABKAMSDAoESGFzaBgDIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchManifest), global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchManifest.Parser, new[]{ "FileDatas", "DeleteFilesEntries" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileData), global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileData.Parser, new[]{ "FileName", "FileSize", "FileHash", "PatchesEntries" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchesEntry), global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchesEntry.Parser, new[]{ "Key", "PatchInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchInfo), global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchInfo.Parser, new[]{ "Id", "Tag", "BuildId", "PatchFileSize", "PatchesFileHash", "PatchStartOffset", "PatchLength", "OriginalFileName", "OriginalFileSize", "OriginalFileHash" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFilesEntry), global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFilesEntry.Parser, new[]{ "Key", "DeleteFiles" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFiles), global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFiles.Parser, new[]{ "Infos" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileInfo), global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileInfo.Parser, new[]{ "Name", "Size", "Hash" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PatchManifest : pb::IMessage<PatchManifest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PatchManifest> _parser = new pb::MessageParser<PatchManifest>(() => new PatchManifest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PatchManifest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.SophonPatchManifestProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PatchManifest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PatchManifest(PatchManifest other) : this() {
      fileDatas_ = other.fileDatas_.Clone();
      deleteFilesEntries_ = other.deleteFilesEntries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PatchManifest Clone() {
      return new PatchManifest(this);
    }

    /// <summary>Field number for the "FileDatas" field.</summary>
    public const int FileDatasFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileData> _repeated_fileDatas_codec
        = pb::FieldCodec.ForMessage(10, global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileData.Parser);
    private readonly pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileData> fileDatas_ = new pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileData> FileDatas {
      get { return fileDatas_; }
    }

    /// <summary>Field number for the "DeleteFilesEntries" field.</summary>
    public const int DeleteFilesEntriesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFilesEntry> _repeated_deleteFilesEntries_codec
        = pb::FieldCodec.ForMessage(18, global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFilesEntry.Parser);
    private readonly pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFilesEntry> deleteFilesEntries_ = new pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFilesEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFilesEntry> DeleteFilesEntries {
      get { return deleteFilesEntries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PatchManifest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PatchManifest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!fileDatas_.Equals(other.fileDatas_)) return false;
      if(!deleteFilesEntries_.Equals(other.deleteFilesEntries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= fileDatas_.GetHashCode();
      hash ^= deleteFilesEntries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      fileDatas_.WriteTo(output, _repeated_fileDatas_codec);
      deleteFilesEntries_.WriteTo(output, _repeated_deleteFilesEntries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      fileDatas_.WriteTo(ref output, _repeated_fileDatas_codec);
      deleteFilesEntries_.WriteTo(ref output, _repeated_deleteFilesEntries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += fileDatas_.CalculateSize(_repeated_fileDatas_codec);
      size += deleteFilesEntries_.CalculateSize(_repeated_deleteFilesEntries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PatchManifest other) {
      if (other == null) {
        return;
      }
      fileDatas_.Add(other.fileDatas_);
      deleteFilesEntries_.Add(other.deleteFilesEntries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            fileDatas_.AddEntriesFrom(input, _repeated_fileDatas_codec);
            break;
          }
          case 18: {
            deleteFilesEntries_.AddEntriesFrom(input, _repeated_deleteFilesEntries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            fileDatas_.AddEntriesFrom(ref input, _repeated_fileDatas_codec);
            break;
          }
          case 18: {
            deleteFilesEntries_.AddEntriesFrom(ref input, _repeated_deleteFilesEntries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FileData : pb::IMessage<FileData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FileData> _parser = new pb::MessageParser<FileData>(() => new FileData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FileData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.SophonPatchManifestProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FileData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FileData(FileData other) : this() {
      fileName_ = other.fileName_;
      fileSize_ = other.fileSize_;
      fileHash_ = other.fileHash_;
      patchesEntries_ = other.patchesEntries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FileData Clone() {
      return new FileData(this);
    }

    /// <summary>Field number for the "FileName" field.</summary>
    public const int FileNameFieldNumber = 1;
    private string fileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FileName {
      get { return fileName_; }
      set {
        fileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FileSize" field.</summary>
    public const int FileSizeFieldNumber = 2;
    private long fileSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FileSize {
      get { return fileSize_; }
      set {
        fileSize_ = value;
      }
    }

    /// <summary>Field number for the "FileHash" field.</summary>
    public const int FileHashFieldNumber = 3;
    private string fileHash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FileHash {
      get { return fileHash_; }
      set {
        fileHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PatchesEntries" field.</summary>
    public const int PatchesEntriesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchesEntry> _repeated_patchesEntries_codec
        = pb::FieldCodec.ForMessage(34, global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchesEntry.Parser);
    private readonly pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchesEntry> patchesEntries_ = new pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchesEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchesEntry> PatchesEntries {
      get { return patchesEntries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FileData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FileData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FileName != other.FileName) return false;
      if (FileSize != other.FileSize) return false;
      if (FileHash != other.FileHash) return false;
      if(!patchesEntries_.Equals(other.patchesEntries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FileName.Length != 0) hash ^= FileName.GetHashCode();
      if (FileSize != 0L) hash ^= FileSize.GetHashCode();
      if (FileHash.Length != 0) hash ^= FileHash.GetHashCode();
      hash ^= patchesEntries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FileName);
      }
      if (FileSize != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(FileSize);
      }
      if (FileHash.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FileHash);
      }
      patchesEntries_.WriteTo(output, _repeated_patchesEntries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FileName);
      }
      if (FileSize != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(FileSize);
      }
      if (FileHash.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FileHash);
      }
      patchesEntries_.WriteTo(ref output, _repeated_patchesEntries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileName);
      }
      if (FileSize != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FileSize);
      }
      if (FileHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileHash);
      }
      size += patchesEntries_.CalculateSize(_repeated_patchesEntries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FileData other) {
      if (other == null) {
        return;
      }
      if (other.FileName.Length != 0) {
        FileName = other.FileName;
      }
      if (other.FileSize != 0L) {
        FileSize = other.FileSize;
      }
      if (other.FileHash.Length != 0) {
        FileHash = other.FileHash;
      }
      patchesEntries_.Add(other.patchesEntries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FileName = input.ReadString();
            break;
          }
          case 16: {
            FileSize = input.ReadInt64();
            break;
          }
          case 26: {
            FileHash = input.ReadString();
            break;
          }
          case 34: {
            patchesEntries_.AddEntriesFrom(input, _repeated_patchesEntries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FileName = input.ReadString();
            break;
          }
          case 16: {
            FileSize = input.ReadInt64();
            break;
          }
          case 26: {
            FileHash = input.ReadString();
            break;
          }
          case 34: {
            patchesEntries_.AddEntriesFrom(ref input, _repeated_patchesEntries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PatchesEntry : pb::IMessage<PatchesEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PatchesEntry> _parser = new pb::MessageParser<PatchesEntry>(() => new PatchesEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PatchesEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.SophonPatchManifestProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PatchesEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PatchesEntry(PatchesEntry other) : this() {
      key_ = other.key_;
      patchInfo_ = other.patchInfo_ != null ? other.patchInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PatchesEntry Clone() {
      return new PatchesEntry(this);
    }

    /// <summary>Field number for the "Key" field.</summary>
    public const int KeyFieldNumber = 1;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PatchInfo" field.</summary>
    public const int PatchInfoFieldNumber = 2;
    private global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchInfo patchInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchInfo PatchInfo {
      get { return patchInfo_; }
      set {
        patchInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PatchesEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PatchesEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (!object.Equals(PatchInfo, other.PatchInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (patchInfo_ != null) hash ^= PatchInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (patchInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PatchInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (patchInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PatchInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (patchInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PatchInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PatchesEntry other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.patchInfo_ != null) {
        if (patchInfo_ == null) {
          PatchInfo = new global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchInfo();
        }
        PatchInfo.MergeFrom(other.PatchInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            if (patchInfo_ == null) {
              PatchInfo = new global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchInfo();
            }
            input.ReadMessage(PatchInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            if (patchInfo_ == null) {
              PatchInfo = new global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.PatchInfo();
            }
            input.ReadMessage(PatchInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PatchInfo : pb::IMessage<PatchInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PatchInfo> _parser = new pb::MessageParser<PatchInfo>(() => new PatchInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PatchInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.SophonPatchManifestProtoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PatchInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PatchInfo(PatchInfo other) : this() {
      id_ = other.id_;
      tag_ = other.tag_;
      buildId_ = other.buildId_;
      patchFileSize_ = other.patchFileSize_;
      patchesFileHash_ = other.patchesFileHash_;
      patchStartOffset_ = other.patchStartOffset_;
      patchLength_ = other.patchLength_;
      originalFileName_ = other.originalFileName_;
      originalFileSize_ = other.originalFileSize_;
      originalFileHash_ = other.originalFileHash_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PatchInfo Clone() {
      return new PatchInfo(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Tag" field.</summary>
    public const int TagFieldNumber = 2;
    private string tag_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Tag {
      get { return tag_; }
      set {
        tag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BuildId" field.</summary>
    public const int BuildIdFieldNumber = 3;
    private string buildId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BuildId {
      get { return buildId_; }
      set {
        buildId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PatchFileSize" field.</summary>
    public const int PatchFileSizeFieldNumber = 4;
    private long patchFileSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PatchFileSize {
      get { return patchFileSize_; }
      set {
        patchFileSize_ = value;
      }
    }

    /// <summary>Field number for the "PatchesFileHash" field.</summary>
    public const int PatchesFileHashFieldNumber = 5;
    private string patchesFileHash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PatchesFileHash {
      get { return patchesFileHash_; }
      set {
        patchesFileHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PatchStartOffset" field.</summary>
    public const int PatchStartOffsetFieldNumber = 6;
    private long patchStartOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PatchStartOffset {
      get { return patchStartOffset_; }
      set {
        patchStartOffset_ = value;
      }
    }

    /// <summary>Field number for the "PatchLength" field.</summary>
    public const int PatchLengthFieldNumber = 7;
    private long patchLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PatchLength {
      get { return patchLength_; }
      set {
        patchLength_ = value;
      }
    }

    /// <summary>Field number for the "OriginalFileName" field.</summary>
    public const int OriginalFileNameFieldNumber = 8;
    private string originalFileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OriginalFileName {
      get { return originalFileName_; }
      set {
        originalFileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "OriginalFileSize" field.</summary>
    public const int OriginalFileSizeFieldNumber = 9;
    private long originalFileSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OriginalFileSize {
      get { return originalFileSize_; }
      set {
        originalFileSize_ = value;
      }
    }

    /// <summary>Field number for the "OriginalFileHash" field.</summary>
    public const int OriginalFileHashFieldNumber = 10;
    private string originalFileHash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OriginalFileHash {
      get { return originalFileHash_; }
      set {
        originalFileHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PatchInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PatchInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Tag != other.Tag) return false;
      if (BuildId != other.BuildId) return false;
      if (PatchFileSize != other.PatchFileSize) return false;
      if (PatchesFileHash != other.PatchesFileHash) return false;
      if (PatchStartOffset != other.PatchStartOffset) return false;
      if (PatchLength != other.PatchLength) return false;
      if (OriginalFileName != other.OriginalFileName) return false;
      if (OriginalFileSize != other.OriginalFileSize) return false;
      if (OriginalFileHash != other.OriginalFileHash) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Tag.Length != 0) hash ^= Tag.GetHashCode();
      if (BuildId.Length != 0) hash ^= BuildId.GetHashCode();
      if (PatchFileSize != 0L) hash ^= PatchFileSize.GetHashCode();
      if (PatchesFileHash.Length != 0) hash ^= PatchesFileHash.GetHashCode();
      if (PatchStartOffset != 0L) hash ^= PatchStartOffset.GetHashCode();
      if (PatchLength != 0L) hash ^= PatchLength.GetHashCode();
      if (OriginalFileName.Length != 0) hash ^= OriginalFileName.GetHashCode();
      if (OriginalFileSize != 0L) hash ^= OriginalFileSize.GetHashCode();
      if (OriginalFileHash.Length != 0) hash ^= OriginalFileHash.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Tag.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Tag);
      }
      if (BuildId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BuildId);
      }
      if (PatchFileSize != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(PatchFileSize);
      }
      if (PatchesFileHash.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PatchesFileHash);
      }
      if (PatchStartOffset != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(PatchStartOffset);
      }
      if (PatchLength != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(PatchLength);
      }
      if (OriginalFileName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(OriginalFileName);
      }
      if (OriginalFileSize != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(OriginalFileSize);
      }
      if (OriginalFileHash.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(OriginalFileHash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Tag.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Tag);
      }
      if (BuildId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BuildId);
      }
      if (PatchFileSize != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(PatchFileSize);
      }
      if (PatchesFileHash.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PatchesFileHash);
      }
      if (PatchStartOffset != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(PatchStartOffset);
      }
      if (PatchLength != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(PatchLength);
      }
      if (OriginalFileName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(OriginalFileName);
      }
      if (OriginalFileSize != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(OriginalFileSize);
      }
      if (OriginalFileHash.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(OriginalFileHash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Tag.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tag);
      }
      if (BuildId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BuildId);
      }
      if (PatchFileSize != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PatchFileSize);
      }
      if (PatchesFileHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PatchesFileHash);
      }
      if (PatchStartOffset != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PatchStartOffset);
      }
      if (PatchLength != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PatchLength);
      }
      if (OriginalFileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OriginalFileName);
      }
      if (OriginalFileSize != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OriginalFileSize);
      }
      if (OriginalFileHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OriginalFileHash);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PatchInfo other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Tag.Length != 0) {
        Tag = other.Tag;
      }
      if (other.BuildId.Length != 0) {
        BuildId = other.BuildId;
      }
      if (other.PatchFileSize != 0L) {
        PatchFileSize = other.PatchFileSize;
      }
      if (other.PatchesFileHash.Length != 0) {
        PatchesFileHash = other.PatchesFileHash;
      }
      if (other.PatchStartOffset != 0L) {
        PatchStartOffset = other.PatchStartOffset;
      }
      if (other.PatchLength != 0L) {
        PatchLength = other.PatchLength;
      }
      if (other.OriginalFileName.Length != 0) {
        OriginalFileName = other.OriginalFileName;
      }
      if (other.OriginalFileSize != 0L) {
        OriginalFileSize = other.OriginalFileSize;
      }
      if (other.OriginalFileHash.Length != 0) {
        OriginalFileHash = other.OriginalFileHash;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Tag = input.ReadString();
            break;
          }
          case 26: {
            BuildId = input.ReadString();
            break;
          }
          case 32: {
            PatchFileSize = input.ReadInt64();
            break;
          }
          case 42: {
            PatchesFileHash = input.ReadString();
            break;
          }
          case 48: {
            PatchStartOffset = input.ReadInt64();
            break;
          }
          case 56: {
            PatchLength = input.ReadInt64();
            break;
          }
          case 66: {
            OriginalFileName = input.ReadString();
            break;
          }
          case 72: {
            OriginalFileSize = input.ReadInt64();
            break;
          }
          case 82: {
            OriginalFileHash = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Tag = input.ReadString();
            break;
          }
          case 26: {
            BuildId = input.ReadString();
            break;
          }
          case 32: {
            PatchFileSize = input.ReadInt64();
            break;
          }
          case 42: {
            PatchesFileHash = input.ReadString();
            break;
          }
          case 48: {
            PatchStartOffset = input.ReadInt64();
            break;
          }
          case 56: {
            PatchLength = input.ReadInt64();
            break;
          }
          case 66: {
            OriginalFileName = input.ReadString();
            break;
          }
          case 72: {
            OriginalFileSize = input.ReadInt64();
            break;
          }
          case 82: {
            OriginalFileHash = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DeleteFilesEntry : pb::IMessage<DeleteFilesEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeleteFilesEntry> _parser = new pb::MessageParser<DeleteFilesEntry>(() => new DeleteFilesEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeleteFilesEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.SophonPatchManifestProtoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteFilesEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteFilesEntry(DeleteFilesEntry other) : this() {
      key_ = other.key_;
      deleteFiles_ = other.deleteFiles_ != null ? other.deleteFiles_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteFilesEntry Clone() {
      return new DeleteFilesEntry(this);
    }

    /// <summary>Field number for the "Key" field.</summary>
    public const int KeyFieldNumber = 1;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DeleteFiles" field.</summary>
    public const int DeleteFilesFieldNumber = 2;
    private global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFiles deleteFiles_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFiles DeleteFiles {
      get { return deleteFiles_; }
      set {
        deleteFiles_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeleteFilesEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeleteFilesEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (!object.Equals(DeleteFiles, other.DeleteFiles)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (deleteFiles_ != null) hash ^= DeleteFiles.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (deleteFiles_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DeleteFiles);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (deleteFiles_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DeleteFiles);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (deleteFiles_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeleteFiles);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeleteFilesEntry other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.deleteFiles_ != null) {
        if (deleteFiles_ == null) {
          DeleteFiles = new global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFiles();
        }
        DeleteFiles.MergeFrom(other.DeleteFiles);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            if (deleteFiles_ == null) {
              DeleteFiles = new global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFiles();
            }
            input.ReadMessage(DeleteFiles);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            if (deleteFiles_ == null) {
              DeleteFiles = new global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.DeleteFiles();
            }
            input.ReadMessage(DeleteFiles);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DeleteFiles : pb::IMessage<DeleteFiles>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeleteFiles> _parser = new pb::MessageParser<DeleteFiles>(() => new DeleteFiles());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeleteFiles> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.SophonPatchManifestProtoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteFiles() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteFiles(DeleteFiles other) : this() {
      infos_ = other.infos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteFiles Clone() {
      return new DeleteFiles(this);
    }

    /// <summary>Field number for the "Infos" field.</summary>
    public const int InfosFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileInfo> _repeated_infos_codec
        = pb::FieldCodec.ForMessage(10, global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileInfo.Parser);
    private readonly pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileInfo> infos_ = new pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.FileInfo> Infos {
      get { return infos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeleteFiles);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeleteFiles other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!infos_.Equals(other.infos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= infos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      infos_.WriteTo(output, _repeated_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      infos_.WriteTo(ref output, _repeated_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += infos_.CalculateSize(_repeated_infos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeleteFiles other) {
      if (other == null) {
        return;
      }
      infos_.Add(other.infos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            infos_.AddEntriesFrom(input, _repeated_infos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            infos_.AddEntriesFrom(ref input, _repeated_infos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FileInfo : pb::IMessage<FileInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FileInfo> _parser = new pb::MessageParser<FileInfo>(() => new FileInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FileInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Snap.Hutao.Web.Hoyolab.Takumi.Downloader.Proto.SophonPatchManifestProtoReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FileInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FileInfo(FileInfo other) : this() {
      name_ = other.name_;
      size_ = other.size_;
      hash_ = other.hash_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FileInfo Clone() {
      return new FileInfo(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Size" field.</summary>
    public const int SizeFieldNumber = 2;
    private long size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "Hash" field.</summary>
    public const int HashFieldNumber = 3;
    private string hash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Hash {
      get { return hash_; }
      set {
        hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FileInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FileInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Size != other.Size) return false;
      if (Hash != other.Hash) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Size != 0L) hash ^= Size.GetHashCode();
      if (Hash.Length != 0) hash ^= Hash.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Size != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Size);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Hash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Size != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Size);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Hash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Size != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Size);
      }
      if (Hash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Hash);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FileInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Size != 0L) {
        Size = other.Size;
      }
      if (other.Hash.Length != 0) {
        Hash = other.Hash;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Size = input.ReadInt64();
            break;
          }
          case 26: {
            Hash = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Size = input.ReadInt64();
            break;
          }
          case 26: {
            Hash = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
