//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snap.Hutao.Resource.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SH() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snap.Hutao.Resource.Localization.SH", typeof(SH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 胡桃 Dev {0} 的本地化字符串。
        /// </summary>
        internal static string AppDevNameAndVersion {
            get {
                return ResourceManager.GetString("AppDevNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胡桃 {0} 的本地化字符串。
        /// </summary>
        internal static string AppNameAndVersion {
            get {
                return ResourceManager.GetString("AppNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string ContentDialogCancelCloseButtonText {
            get {
                return ResourceManager.GetString("ContentDialogCancelCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string ContentDialogCompletePrimaryButtonText {
            get {
                return ResourceManager.GetString("ContentDialogCompletePrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string ContentDialogConfirmPrimaryButtonText {
            get {
                return ResourceManager.GetString("ContentDialogConfirmPrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string ContentDialogSavePrimaryButtonText {
            get {
                return ResourceManager.GetString("ContentDialogSavePrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的 Uri 的本地化字符串。
        /// </summary>
        internal static string ControlImageCachedImageInvalidResourceUri {
            get {
                return ResourceManager.GetString("ControlImageCachedImageInvalidResourceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP GET {0} 的本地化字符串。
        /// </summary>
        internal static string ControlImageCompositionImageHttpRequest {
            get {
                return ResourceManager.GetString("ControlImageCompositionImageHttpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 CompositionImage 的源时发生异常 的本地化字符串。
        /// </summary>
        internal static string ControlImageCompositionImageSystemException {
            get {
                return ResourceManager.GetString("ControlImageCompositionImageSystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网格 的本地化字符串。
        /// </summary>
        internal static string ControlPanelPanelSelectorDropdownGridName {
            get {
                return ResourceManager.GetString("ControlPanelPanelSelectorDropdownGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表 的本地化字符串。
        /// </summary>
        internal static string ControlPanelPanelSelectorDropdownListName {
            get {
                return ResourceManager.GetString("ControlPanelPanelSelectorDropdownListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户数据已损坏: {0} 的本地化字符串。
        /// </summary>
        internal static string CoreExceptionServiceUserdataCorruptedMessage {
            get {
                return ResourceManager.GetString("CoreExceptionServiceUserdataCorruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请勿在管理员模式下使用此功能 {0} 的本地化字符串。
        /// </summary>
        internal static string CoreIOPickerExtensionPickerExceptionInfoBarMessage {
            get {
                return ResourceManager.GetString("CoreIOPickerExtensionPickerExceptionInfoBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开文件选择器 的本地化字符串。
        /// </summary>
        internal static string CoreIOPickerExtensionPickerExceptionInfoBarTitle {
            get {
                return ResourceManager.GetString("CoreIOPickerExtensionPickerExceptionInfoBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        internal static string CoreJumpListHelperLaunchGameItemDisplayName {
            get {
                return ResourceManager.GetString("CoreJumpListHelperLaunchGameItemDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷操作 的本地化字符串。
        /// </summary>
        internal static string CoreJumpListHelperLaunchGameItemGroupName {
            get {
                return ResourceManager.GetString("CoreJumpListHelperLaunchGameItemGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胡桃实时便笺刷新任务 | 请勿编辑或删除。 的本地化字符串。
        /// </summary>
        internal static string CoreScheduleTaskHelperDailyNoteRefreshTaskDescription {
            get {
                return ResourceManager.GetString("CoreScheduleTaskHelperDailyNoteRefreshTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信号量已经被释放，操作取消 的本地化字符串。
        /// </summary>
        internal static string CoreThreadingSemaphoreSlimDisposed {
            get {
                return ResourceManager.GetString("CoreThreadingSemaphoreSlimDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检测到 WebView2 运行时 的本地化字符串。
        /// </summary>
        internal static string CoreWebView2HelperVersionUndetected {
            get {
                return ResourceManager.GetString("CoreWebView2HelperVersionUndetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单个成就存档内发现多个相同的成就 Id 的本地化字符串。
        /// </summary>
        internal static string ServiceAchievementUserdataCorruptedInnerIdNotUnique {
            get {
                return ResourceManager.GetString("ServiceAchievementUserdataCorruptedInnerIdNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始游戏 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierActionLaunchGameButton {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierActionLaunchGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我知道了 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierActionLaunchGameDismiss {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierActionLaunchGameDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求异常 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierAttribution {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日委托 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierDailyTask {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierDailyTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奖励未领取 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierDailyTaskHint {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierDailyTaskHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探索派遣 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierExpedition {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierExpeditionAdaptiveHint {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierExpeditionAdaptiveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探索派遣已完成 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierExpeditionHint {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierExpeditionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 洞天宝钱 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierHomeCoin {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierHomeCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前洞天宝钱：{0} 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierHomeCoinCurrent {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierHomeCoinCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多个提醒项达到设定值 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierMultiValueReached {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierMultiValueReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原粹树脂 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierResin {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierResin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前原粹树脂：{0} 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierResinCurrent {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierResinCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时便笺提醒 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierTitle {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参量质变仪 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierTransformer {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierTransformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备完成 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierTransformerAdaptiveHint {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierTransformerAdaptiveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参量质变仪已准备完成 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierTransformerHint {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierTransformerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取祈愿记录: {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogArchiveCollectionUserdataCorruptedMessage {
            get {
                return ResourceManager.GetString("ServiceGachaLogArchiveCollectionUserdataCorruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取祈愿记录 End Id 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogEndIdUserdataCorruptedMessage {
            get {
                return ResourceManager.GetString("ServiceGachaLogEndIdUserdataCorruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色活动 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogFactoryAvatarWishName {
            get {
                return ResourceManager.GetString("ServiceGachaLogFactoryAvatarWishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奔行世间 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogFactoryPermanentWishName {
            get {
                return ResourceManager.GetString("ServiceGachaLogFactoryPermanentWishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神铸赋形 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogFactoryWeaponWishName {
            get {
                return ResourceManager.GetString("ServiceGachaLogFactoryWeaponWishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求验证密钥失败 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogUrlProviderAuthkeyRequestFailed {
            get {
                return ResourceManager.GetString("ServiceGachaLogUrlProviderAuthkeyRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未正确提供原神路径，或当前设置的路径不正确 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogUrlProviderCachePathInvalid {
            get {
                return ResourceManager.GetString("ServiceGachaLogUrlProviderCachePathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到原神内置浏览器缓存路径：\n{0} 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogUrlProviderCachePathNotFound {
            get {
                return ResourceManager.GetString("ServiceGachaLogUrlProviderCachePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到可用的 Url 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogUrlProviderCacheUrlNotFound {
            get {
                return ResourceManager.GetString("ServiceGachaLogUrlProviderCacheUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供的 Url 无效 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogUrlProviderManualInputInvalid {
            get {
                return ResourceManager.GetString("ServiceGachaLogUrlProviderManualInputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在多个匹配账号，请删除重复的账号 的本地化字符串。
        /// </summary>
        internal static string ServiceGameDetectGameAccountMultiMatched {
            get {
                return ResourceManager.GetString("ServiceGameDetectGameAccountMultiMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询游戏资源信息 的本地化字符串。
        /// </summary>
        internal static string ServiceGameEnsureGameResourceQueryResourceInformation {
            get {
                return ResourceManager.GetString("ServiceGameEnsureGameResourceQueryResourceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏文件操作失败: {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceGameFileOperationExceptionMessage {
            get {
                return ResourceManager.GetString("ServiceGameFileOperationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择游戏本体 的本地化字符串。
        /// </summary>
        internal static string ServiceGameLocatorFileOpenPickerCommitText {
            get {
                return ResourceManager.GetString("ServiceGameLocatorFileOpenPickerCommitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到 Unity 日志文件 的本地化字符串。
        /// </summary>
        internal static string ServiceGameLocatorUnityLogFileNotFound {
            get {
                return ResourceManager.GetString("ServiceGameLocatorUnityLogFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 Unity 日志文件中找不到游戏路径 的本地化字符串。
        /// </summary>
        internal static string ServiceGameLocatorUnityLogGamePathNotFound {
            get {
                return ResourceManager.GetString("ServiceGameLocatorUnityLogGamePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 Package Version 的本地化字符串。
        /// </summary>
        internal static string ServiceGamePackageRequestPackageVerion {
            get {
                return ResourceManager.GetString("ServiceGamePackageRequestPackageVerion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 Package Version 失败 的本地化字符串。
        /// </summary>
        internal static string ServiceGamePackageRequestPackageVerionFailed {
            get {
                return ResourceManager.GetString("ServiceGamePackageRequestPackageVerionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到游戏路径，请前往设置修改 的本地化字符串。
        /// </summary>
        internal static string ServiceGamePathLocateFailed {
            get {
                return ResourceManager.GetString("ServiceGamePathLocateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到游戏配置文件 {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceGameSetMultiChannelConfigFileNotFound {
            get {
                return ResourceManager.GetString("ServiceGameSetMultiChannelConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法读取或保存配置文件，请以管理员模式重试 的本地化字符串。
        /// </summary>
        internal static string ServiceGameSetMultiChannelUnauthorizedAccess {
            get {
                return ResourceManager.GetString("ServiceGameSetMultiChannelUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元数据服务尚未初始化，或初始化失败 的本地化字符串。
        /// </summary>
        internal static string ServiceMetadataNotInitialized {
            get {
                return ResourceManager.GetString("ServiceMetadataNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元数据校验文件解析失败 的本地化字符串。
        /// </summary>
        internal static string ServiceMetadataParseFailed {
            get {
                return ResourceManager.GetString("ServiceMetadataParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元数据校验文件下载失败 的本地化字符串。
        /// </summary>
        internal static string ServiceMetadataRequestFailed {
            get {
                return ResourceManager.GetString("ServiceMetadataRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未选择任何用户以及角色 的本地化字符串。
        /// </summary>
        internal static string ServiceUserAndRoleUnselected {
            get {
                return ResourceManager.GetString("ServiceUserAndRoleUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多个用户记录为选中状态 的本地化字符串。
        /// </summary>
        internal static string ServiceUserCurrentMultiMatched {
            get {
                return ResourceManager.GetString("ServiceUserCurrentMultiMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 {0} 状态保存失败 的本地化字符串。
        /// </summary>
        internal static string ServiceUserCurrentUpdateAndSaveFailed {
            get {
                return ResourceManager.GetString("ServiceUserCurrentUpdateAndSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的 Cookie 必须包含 Mid 的本地化字符串。
        /// </summary>
        internal static string ServiceUserProcessCookieNoMid {
            get {
                return ResourceManager.GetString("ServiceUserProcessCookieNoMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的 Cookie 必须包含 Stoken 的本地化字符串。
        /// </summary>
        internal static string ServiceUserProcessCookieNoStoken {
            get {
                return ResourceManager.GetString("ServiceUserProcessCookieNoStoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的 Cookie 无法获取用户信息 的本地化字符串。
        /// </summary>
        internal static string ServiceUserProcessCookieRequestUserInfoFailed {
            get {
                return ResourceManager.GetString("ServiceUserProcessCookieRequestUserInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的角色 的本地化字符串。
        /// </summary>
        internal static string ViewAvatarPropertyHeader {
            get {
                return ResourceManager.GetString("ViewAvatarPropertyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中，请稍候 的本地化字符串。
        /// </summary>
        internal static string ViewControlLoadingText {
            get {
                return ResourceManager.GetString("ViewControlLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三星 的本地化字符串。
        /// </summary>
        internal static string ViewControlStatisticsCardBlueText {
            get {
                return ResourceManager.GetString("ViewControlStatisticsCardBlueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保底 的本地化字符串。
        /// </summary>
        internal static string ViewControlStatisticsCardGuarenteeText {
            get {
                return ResourceManager.GetString("ViewControlStatisticsCardGuarenteeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 五星平均抽数 的本地化字符串。
        /// </summary>
        internal static string ViewControlStatisticsCardOrangeAveragePullText {
            get {
                return ResourceManager.GetString("ViewControlStatisticsCardOrangeAveragePullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 五星 的本地化字符串。
        /// </summary>
        internal static string ViewControlStatisticsCardOrangeText {
            get {
                return ResourceManager.GetString("ViewControlStatisticsCardOrangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽 的本地化字符串。
        /// </summary>
        internal static string ViewControlStatisticsCardPullText {
            get {
                return ResourceManager.GetString("ViewControlStatisticsCardPullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四星 的本地化字符串。
        /// </summary>
        internal static string ViewControlStatisticsCardPurpleText {
            get {
                return ResourceManager.GetString("ViewControlStatisticsCardPurpleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UP 平均抽数 的本地化字符串。
        /// </summary>
        internal static string ViewControlStatisticsCardUpAveragePullText {
            get {
                return ResourceManager.GetString("ViewControlStatisticsCardUpAveragePullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UP 的本地化字符串。
        /// </summary>
        internal static string ViewControlStatisticsCardUpText {
            get {
                return ResourceManager.GetString("ViewControlStatisticsCardUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此处输入 的本地化字符串。
        /// </summary>
        internal static string ViewDialogAchievementArchiveCreateInputPlaceholder {
            get {
                return ResourceManager.GetString("ViewDialogAchievementArchiveCreateInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置成就存档的名称 的本地化字符串。
        /// </summary>
        internal static string ViewDialogAchievementArchiveCreateTitle {
            get {
                return ResourceManager.GetString("ViewDialogAchievementArchiveCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入模式 的本地化字符串。
        /// </summary>
        internal static string ViewDialogAchievementArchiveImportStrategy {
            get {
                return ResourceManager.GetString("ViewDialogAchievementArchiveImportStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贪婪（添加新数据，更新已完成项） 的本地化字符串。
        /// </summary>
        internal static string ViewDialogAchievementArchiveImportStrategyAggressive {
            get {
                return ResourceManager.GetString("ViewDialogAchievementArchiveImportStrategyAggressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 懒惰（添加新数据，跳过已完成项） 的本地化字符串。
        /// </summary>
        internal static string ViewDialogAchievementArchiveImportStrategyLazy {
            get {
                return ResourceManager.GetString("ViewDialogAchievementArchiveImportStrategyLazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 覆盖（删除老数据，添加新的数据） 的本地化字符串。
        /// </summary>
        internal static string ViewDialogAchievementArchiveImportStrategyOverwrite {
            get {
                return ResourceManager.GetString("ViewDialogAchievementArchiveImportStrategyOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为当前存档导入成就 的本地化字符串。
        /// </summary>
        internal static string ViewDialogAchievementArchiveImportTitle {
            get {
                return ResourceManager.GetString("ViewDialogAchievementArchiveImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定当前用户与角色 的本地化字符串。
        /// </summary>
        internal static string ViewDialogCultivateProjectAttachUid {
            get {
                return ResourceManager.GetString("ViewDialogCultivateProjectAttachUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此处输入计划名称 的本地化字符串。
        /// </summary>
        internal static string ViewDialogCultivateProjectInputPlaceholder {
            get {
                return ResourceManager.GetString("ViewDialogCultivateProjectInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新的养成计划 的本地化字符串。
        /// </summary>
        internal static string ViewDialogCultivateProjectTitle {
            get {
                return ResourceManager.GetString("ViewDialogCultivateProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加到当前养成计划 的本地化字符串。
        /// </summary>
        internal static string ViewDialogCultivatePromotionDeltaTitle {
            get {
                return ResourceManager.GetString("ViewDialogCultivatePromotionDeltaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日委托上线提醒 的本地化字符串。
        /// </summary>
        internal static string ViewDialogDailyNoteNotificationDailyTaskNotify {
            get {
                return ResourceManager.GetString("ViewDialogDailyNoteNotificationDailyTaskNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探索派遣完成提醒 的本地化字符串。
        /// </summary>
        internal static string ViewDialogDailyNoteNotificationExpeditionNotify {
            get {
                return ResourceManager.GetString("ViewDialogDailyNoteNotificationExpeditionNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 洞天宝钱提醒阈值 的本地化字符串。
        /// </summary>
        internal static string ViewDialogDailyNoteNotificationHomeCoinNotifyThreshold {
            get {
                return ResourceManager.GetString("ViewDialogDailyNoteNotificationHomeCoinNotifyThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原粹树脂提醒阈值 的本地化字符串。
        /// </summary>
        internal static string ViewDialogDailyNoteNotificationResinNotifyThreshold {
            get {
                return ResourceManager.GetString("ViewDialogDailyNoteNotificationResinNotifyThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在主页显示卡片 的本地化字符串。
        /// </summary>
        internal static string ViewDialogDailyNoteNotificationShowInHomeWidget {
            get {
                return ResourceManager.GetString("ViewDialogDailyNoteNotificationShowInHomeWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置实时便笺通知 的本地化字符串。
        /// </summary>
        internal static string ViewDialogDailyNoteNotificationTitle {
            get {
                return ResourceManager.GetString("ViewDialogDailyNoteNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参量质变仪提醒 的本地化字符串。
        /// </summary>
        internal static string ViewDialogDailyNoteNotificationTransformerNotify {
            get {
                return ResourceManager.GetString("ViewDialogDailyNoteNotificationTransformerNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入祈愿记录 的本地化字符串。
        /// </summary>
        internal static string ViewDialogGachaLogImportTitle {
            get {
                return ResourceManager.GetString("ViewDialogGachaLogImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取祈愿物品中 的本地化字符串。
        /// </summary>
        internal static string ViewDialogGachaLogRefreshProgressTitle {
            get {
                return ResourceManager.GetString("ViewDialogGachaLogRefreshProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入 Url 的本地化字符串。
        /// </summary>
        internal static string ViewDialogGachaLogUrlInputPlaceholder {
            get {
                return ResourceManager.GetString("ViewDialogGachaLogUrlInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动输入祈愿记录 Url 的本地化字符串。
        /// </summary>
        internal static string ViewDialogGachaLogUrlTitle {
            get {
                return ResourceManager.GetString("ViewDialogGachaLogUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 App 的本地化字符串。
        /// </summary>
        internal static string ViewDialogImportExportApp {
            get {
                return ResourceManager.GetString("ViewDialogImportExportApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 App 版本 的本地化字符串。
        /// </summary>
        internal static string ViewDialogImportExportAppVersion {
            get {
                return ResourceManager.GetString("ViewDialogImportExportAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出时间 的本地化字符串。
        /// </summary>
        internal static string ViewDialogImportExportTime {
            get {
                return ResourceManager.GetString("ViewDialogImportExportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成就个数 的本地化字符串。
        /// </summary>
        internal static string ViewDialogImportUIAFExportListCount {
            get {
                return ResourceManager.GetString("ViewDialogImportUIAFExportListCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UIAF 版本 的本地化字符串。
        /// </summary>
        internal static string ViewDialogImportUIAFExportUIAFVersion {
            get {
                return ResourceManager.GetString("ViewDialogImportUIAFExportUIAFVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录条数 的本地化字符串。
        /// </summary>
        internal static string ViewDialogImportUIGFExportListCount {
            get {
                return ResourceManager.GetString("ViewDialogImportUIGFExportListCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UID 的本地化字符串。
        /// </summary>
        internal static string ViewDialogImportUIGFExportUid {
            get {
                return ResourceManager.GetString("ViewDialogImportUIGFExportUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UIGF 版本 的本地化字符串。
        /// </summary>
        internal static string ViewDialogImportUIGFExportUIGFVersion {
            get {
                return ResourceManager.GetString("ViewDialogImportUIGFExportUIGFVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此处输入名称 的本地化字符串。
        /// </summary>
        internal static string ViewDialogLaunchGameAccountInputPlaceholder {
            get {
                return ResourceManager.GetString("ViewDialogLaunchGameAccountInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为账号命名 的本地化字符串。
        /// </summary>
        internal static string ViewDialogLaunchGameAccountTitle {
            get {
                return ResourceManager.GetString("ViewDialogLaunchGameAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换可能需要花费一段时间，请勿关闭胡桃 的本地化字符串。
        /// </summary>
        internal static string ViewDialogLaunchGamePackageConvertHint {
            get {
                return ResourceManager.GetString("ViewDialogLaunchGamePackageConvertHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换客户端 的本地化字符串。
        /// </summary>
        internal static string ViewDialogLaunchGamePackageConvertTitle {
            get {
                return ResourceManager.GetString("ViewDialogLaunchGamePackageConvertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即前往 的本地化字符串。
        /// </summary>
        internal static string ViewDialogUserDocumentAction {
            get {
                return ResourceManager.GetString("ViewDialogUserDocumentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入文档页面并按指示操作 的本地化字符串。
        /// </summary>
        internal static string ViewDialogUserDocumentDescription {
            get {
                return ResourceManager.GetString("ViewDialogUserDocumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作文档 的本地化字符串。
        /// </summary>
        internal static string ViewDialogUserDocumentHeader {
            get {
                return ResourceManager.GetString("ViewDialogUserDocumentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此处输入包含 Stoken 的 Cookie 的本地化字符串。
        /// </summary>
        internal static string ViewDialogUserInputPlaceholder {
            get {
                return ResourceManager.GetString("ViewDialogUserInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新存档 的本地化字符串。
        /// </summary>
        internal static string ViewPageAchievementAddArchive {
            get {
                return ResourceManager.GetString("ViewPageAchievementAddArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新存档以继续 的本地化字符串。
        /// </summary>
        internal static string ViewPageAchievementAddArchiveHint {
            get {
                return ResourceManager.GetString("ViewPageAchievementAddArchiveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string ViewPageAchievementExportLabel {
            get {
                return ResourceManager.GetString("ViewPageAchievementExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从剪贴板导入 的本地化字符串。
        /// </summary>
        internal static string ViewPageAchievementImportFromClipboard {
            get {
                return ResourceManager.GetString("ViewPageAchievementImportFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从 UIAF 文件导入 的本地化字符串。
        /// </summary>
        internal static string ViewPageAchievementImportFromFile {
            get {
                return ResourceManager.GetString("ViewPageAchievementImportFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string ViewPageAchievementImportLabel {
            get {
                return ResourceManager.GetString("ViewPageAchievementImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除当前存档 的本地化字符串。
        /// </summary>
        internal static string ViewPageAchievementRemoveArchive {
            get {
                return ResourceManager.GetString("ViewPageAchievementRemoveArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索成就名称，描述或编号 的本地化字符串。
        /// </summary>
        internal static string ViewPageAchievementSearchPlaceholder {
            get {
                return ResourceManager.GetString("ViewPageAchievementSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先未完成 的本地化字符串。
        /// </summary>
        internal static string ViewPageAchievementSortIncompletedItemsFirst {
            get {
                return ResourceManager.GetString("ViewPageAchievementSortIncompletedItemsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动公告 的本地化字符串。
        /// </summary>
        internal static string ViewPageAnnouncementActivity {
            get {
                return ResourceManager.GetString("ViewPageAnnouncementActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏公告 的本地化字符串。
        /// </summary>
        internal static string ViewPageAnnouncementGame {
            get {
                return ResourceManager.GetString("ViewPageAnnouncementGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圣遗物评分 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyArtifactScore {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyArtifactScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双暴评分 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyCritScore {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyCritScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未获取任何角色信息 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyDefaultDescription {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出图片 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyExportAsImage {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyExportAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色属性 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyHeader {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始词条 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyPrimaryProperties {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyPrimaryProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyRefreshAction {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyRefreshAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从 Enka API 同步 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyRefreshFromEnkaApi {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyRefreshFromEnkaApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步游戏内角色橱窗中的信息 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyRefreshFromEnkaApiDescription {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyRefreshFromEnkaApiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从米游社养成计算同步 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyRefreshFromHoyolabCalculate {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyRefreshFromHoyolabCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步角色天赋信息 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyRefreshFromHoyolabCalculateDescription {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyRefreshFromHoyolabCalculateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从米游社我的角色同步 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyRefreshFromHoyolabGameRecord {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyRefreshFromHoyolabGameRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步角色天赋外的大部分信息 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyRefreshFromHoyolabGameRecordDescription {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyRefreshFromHoyolabGameRecordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评分 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertyScore {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertyScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强化词条 的本地化字符串。
        /// </summary>
        internal static string ViewPageAvatarPropertySecondaryProperties {
            get {
                return ResourceManager.GetString("ViewPageAvatarPropertySecondaryProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 养成计算 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivateCalculate {
            get {
                return ResourceManager.GetString("ViewPageCultivateCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationAddAction {
            get {
                return ResourceManager.GetString("ViewPageCultivationAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建计划 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationAddProject {
            get {
                return ResourceManager.GetString("ViewPageCultivationAddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建养成计划以继续 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationAddProjectContinue {
            get {
                return ResourceManager.GetString("ViewPageCultivationAddProjectContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稍后可以前往其他页面添加养成计划项 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationAddProjectDescription {
            get {
                return ResourceManager.GetString("ViewPageCultivationAddProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加我的角色与武器到养成计划 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationAvatarPropertyDescription {
            get {
                return ResourceManager.GetString("ViewPageCultivationAvatarPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 养成物品 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationCultivateEntry {
            get {
                return ResourceManager.GetString("ViewPageCultivationCultivateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背包物品 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationInventoryItem {
            get {
                return ResourceManager.GetString("ViewPageCultivationInventoryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 材料清单 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationMaterialList {
            get {
                return ResourceManager.GetString("ViewPageCultivationMaterialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 材料统计 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationMaterialStatistics {
            get {
                return ResourceManager.GetString("ViewPageCultivationMaterialStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前往 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationNavigateAction {
            get {
                return ResourceManager.GetString("ViewPageCultivationNavigateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除清单 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationRemoveEntry {
            get {
                return ResourceManager.GetString("ViewPageCultivationRemoveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除当前计划 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationRemoveProject {
            get {
                return ResourceManager.GetString("ViewPageCultivationRemoveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加任意角色到养成计划 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationWikiAvatarDescription {
            get {
                return ResourceManager.GetString("ViewPageCultivationWikiAvatarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加任意武器到养成计划 的本地化字符串。
        /// </summary>
        internal static string ViewPageCultivationWikiWeaponDescription {
            get {
                return ResourceManager.GetString("ViewPageCultivationWikiWeaponDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色资料 的本地化字符串。
        /// </summary>
        internal static string ViewWikiAvatarHeader {
            get {
                return ResourceManager.GetString("ViewWikiAvatarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 武器资料 的本地化字符串。
        /// </summary>
        internal static string ViewWikiWeaponHeader {
            get {
                return ResourceManager.GetString("ViewWikiWeaponHeader", resourceCulture);
            }
        }
    }
}
