//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snap.Hutao.Resource.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SH() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snap.Hutao.Resource.Localization.SH", typeof(SH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 胡桃 Dev {0} 的本地化字符串。
        /// </summary>
        internal static string AppDevNameAndVersion {
            get {
                return ResourceManager.GetString("AppDevNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胡桃 {0} 的本地化字符串。
        /// </summary>
        internal static string AppNameAndVersion {
            get {
                return ResourceManager.GetString("AppNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的 Uri 的本地化字符串。
        /// </summary>
        internal static string ControlImageCachedImageInvalidResourceUri {
            get {
                return ResourceManager.GetString("ControlImageCachedImageInvalidResourceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP GET {0} 的本地化字符串。
        /// </summary>
        internal static string ControlImageCompositionImageHttpRequest {
            get {
                return ResourceManager.GetString("ControlImageCompositionImageHttpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 CompositionImage 的源时发生异常 的本地化字符串。
        /// </summary>
        internal static string ControlImageCompositionImageSystemException {
            get {
                return ResourceManager.GetString("ControlImageCompositionImageSystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网格 的本地化字符串。
        /// </summary>
        internal static string ControlPanelPanelSelectorDropdownGridName {
            get {
                return ResourceManager.GetString("ControlPanelPanelSelectorDropdownGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表 的本地化字符串。
        /// </summary>
        internal static string ControlPanelPanelSelectorDropdownListName {
            get {
                return ResourceManager.GetString("ControlPanelPanelSelectorDropdownListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户数据已损坏: {0} 的本地化字符串。
        /// </summary>
        internal static string CoreExceptionServiceUserdataCorruptedMessage {
            get {
                return ResourceManager.GetString("CoreExceptionServiceUserdataCorruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请勿在管理员模式下使用此功能 {0} 的本地化字符串。
        /// </summary>
        internal static string CoreIOPickerExtensionPickerExceptionInfoBarMessage {
            get {
                return ResourceManager.GetString("CoreIOPickerExtensionPickerExceptionInfoBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开文件选择器 的本地化字符串。
        /// </summary>
        internal static string CoreIOPickerExtensionPickerExceptionInfoBarTitle {
            get {
                return ResourceManager.GetString("CoreIOPickerExtensionPickerExceptionInfoBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        internal static string CoreJumpListHelperLaunchGameItemDisplayName {
            get {
                return ResourceManager.GetString("CoreJumpListHelperLaunchGameItemDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷操作 的本地化字符串。
        /// </summary>
        internal static string CoreJumpListHelperLaunchGameItemGroupName {
            get {
                return ResourceManager.GetString("CoreJumpListHelperLaunchGameItemGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胡桃实时便笺刷新任务 | 请勿编辑或删除。 的本地化字符串。
        /// </summary>
        internal static string CoreScheduleTaskHelperDailyNoteRefreshTaskDescription {
            get {
                return ResourceManager.GetString("CoreScheduleTaskHelperDailyNoteRefreshTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信号量已经被释放，操作取消 的本地化字符串。
        /// </summary>
        internal static string CoreThreadingSemaphoreSlimDisposed {
            get {
                return ResourceManager.GetString("CoreThreadingSemaphoreSlimDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检测到 WebView2 运行时 的本地化字符串。
        /// </summary>
        internal static string CoreWebView2HelperVersionUndetected {
            get {
                return ResourceManager.GetString("CoreWebView2HelperVersionUndetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string FactoryContentDialogFactoryCancelCloseButtonText {
            get {
                return ResourceManager.GetString("FactoryContentDialogFactoryCancelCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string FactoryContentDialogFactoryConfirmPrimaryButtonText {
            get {
                return ResourceManager.GetString("FactoryContentDialogFactoryConfirmPrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单个成就存档内发现多个相同的成就 Id 的本地化字符串。
        /// </summary>
        internal static string ServiceAchievementUserdataCorruptedInnerIdNotUnique {
            get {
                return ResourceManager.GetString("ServiceAchievementUserdataCorruptedInnerIdNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始游戏 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierActionLaunchGameButton {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierActionLaunchGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我知道了 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierActionLaunchGameDismiss {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierActionLaunchGameDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求异常 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierAttribution {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日委托 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierDailyTask {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierDailyTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奖励未领取 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierDailyTaskHint {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierDailyTaskHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探索派遣 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierExpedition {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierExpeditionAdaptiveHint {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierExpeditionAdaptiveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探索派遣已完成 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierExpeditionHint {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierExpeditionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 洞天宝钱 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierHomeCoin {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierHomeCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前洞天宝钱：{0} 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierHomeCoinCurrent {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierHomeCoinCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多个提醒项达到设定值 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierMultiValueReached {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierMultiValueReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原粹树脂 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierResin {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierResin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前原粹树脂：{0} 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierResinCurrent {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierResinCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时便笺提醒 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierTitle {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参量质变仪 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierTransformer {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierTransformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备完成 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierTransformerAdaptiveHint {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierTransformerAdaptiveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参量质变仪已准备完成 的本地化字符串。
        /// </summary>
        internal static string ServiceDailyNoteNotifierTransformerHint {
            get {
                return ResourceManager.GetString("ServiceDailyNoteNotifierTransformerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取祈愿记录: {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogArchiveCollectionUserdataCorruptedMessage {
            get {
                return ResourceManager.GetString("ServiceGachaLogArchiveCollectionUserdataCorruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取祈愿记录 End Id 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogEndIdUserdataCorruptedMessage {
            get {
                return ResourceManager.GetString("ServiceGachaLogEndIdUserdataCorruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色活动 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogFactoryAvatarWishName {
            get {
                return ResourceManager.GetString("ServiceGachaLogFactoryAvatarWishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奔行世间 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogFactoryPermanentWishName {
            get {
                return ResourceManager.GetString("ServiceGachaLogFactoryPermanentWishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神铸赋形 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogFactoryWeaponWishName {
            get {
                return ResourceManager.GetString("ServiceGachaLogFactoryWeaponWishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求验证密钥失败 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogUrlProviderAuthkeyRequestFailed {
            get {
                return ResourceManager.GetString("ServiceGachaLogUrlProviderAuthkeyRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未正确提供原神路径，或当前设置的路径不正确 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogUrlProviderCachePathInvalid {
            get {
                return ResourceManager.GetString("ServiceGachaLogUrlProviderCachePathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到原神内置浏览器缓存路径：\n{0} 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogUrlProviderCachePathNotFound {
            get {
                return ResourceManager.GetString("ServiceGachaLogUrlProviderCachePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到可用的 Url 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogUrlProviderCacheUrlNotFound {
            get {
                return ResourceManager.GetString("ServiceGachaLogUrlProviderCacheUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供的Url无效 的本地化字符串。
        /// </summary>
        internal static string ServiceGachaLogUrlProviderManualInputInvalid {
            get {
                return ResourceManager.GetString("ServiceGachaLogUrlProviderManualInputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在多个匹配账号，请删除重复的账号 的本地化字符串。
        /// </summary>
        internal static string ServiceGameDetectGameAccountMultiMatched {
            get {
                return ResourceManager.GetString("ServiceGameDetectGameAccountMultiMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询游戏资源信息 的本地化字符串。
        /// </summary>
        internal static string ServiceGameEnsureGameResourceQueryResourceInformation {
            get {
                return ResourceManager.GetString("ServiceGameEnsureGameResourceQueryResourceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏文件操作失败: {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceGameFileOperationExceptionMessage {
            get {
                return ResourceManager.GetString("ServiceGameFileOperationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择游戏本体 的本地化字符串。
        /// </summary>
        internal static string ServiceGameLocatorFileOpenPickerCommitText {
            get {
                return ResourceManager.GetString("ServiceGameLocatorFileOpenPickerCommitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到 Unity 日志文件 的本地化字符串。
        /// </summary>
        internal static string ServiceGameLocatorUnityLogFileNotFound {
            get {
                return ResourceManager.GetString("ServiceGameLocatorUnityLogFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 Unity 日志文件中找不到游戏路径 的本地化字符串。
        /// </summary>
        internal static string ServiceGameLocatorUnityLogGamePathNotFound {
            get {
                return ResourceManager.GetString("ServiceGameLocatorUnityLogGamePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 Package Version 的本地化字符串。
        /// </summary>
        internal static string ServiceGamePackageRequestPackageVerion {
            get {
                return ResourceManager.GetString("ServiceGamePackageRequestPackageVerion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 Package Version 失败 的本地化字符串。
        /// </summary>
        internal static string ServiceGamePackageRequestPackageVerionFailed {
            get {
                return ResourceManager.GetString("ServiceGamePackageRequestPackageVerionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到游戏路径，请前往设置修改 的本地化字符串。
        /// </summary>
        internal static string ServiceGamePathLocateFailed {
            get {
                return ResourceManager.GetString("ServiceGamePathLocateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到游戏配置文件 {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceGameSetMultiChannelConfigFileNotFound {
            get {
                return ResourceManager.GetString("ServiceGameSetMultiChannelConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法读取或保存配置文件，请以管理员模式重试 的本地化字符串。
        /// </summary>
        internal static string ServiceGameSetMultiChannelUnauthorizedAccess {
            get {
                return ResourceManager.GetString("ServiceGameSetMultiChannelUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元数据服务尚未初始化，或初始化失败 的本地化字符串。
        /// </summary>
        internal static string ServiceMetadataNotInitialized {
            get {
                return ResourceManager.GetString("ServiceMetadataNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元数据校验文件解析失败 的本地化字符串。
        /// </summary>
        internal static string ServiceMetadataParseFailed {
            get {
                return ResourceManager.GetString("ServiceMetadataParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元数据校验文件下载失败 的本地化字符串。
        /// </summary>
        internal static string ServiceMetadataRequestFailed {
            get {
                return ResourceManager.GetString("ServiceMetadataRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未选择任何用户以及角色 的本地化字符串。
        /// </summary>
        internal static string ServiceUserAndRoleUnselected {
            get {
                return ResourceManager.GetString("ServiceUserAndRoleUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多个用户记录为选中状态 的本地化字符串。
        /// </summary>
        internal static string ServiceUserCurrentMultiMatched {
            get {
                return ResourceManager.GetString("ServiceUserCurrentMultiMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 {0} 状态保存失败 的本地化字符串。
        /// </summary>
        internal static string ServiceUserCurrentUpdateAndSaveFailed {
            get {
                return ResourceManager.GetString("ServiceUserCurrentUpdateAndSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的 Cookie 必须包含 Mid 的本地化字符串。
        /// </summary>
        internal static string ServiceUserProcessCookieNoMid {
            get {
                return ResourceManager.GetString("ServiceUserProcessCookieNoMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的 Cookie 必须包含 Stoken 的本地化字符串。
        /// </summary>
        internal static string ServiceUserProcessCookieNoStoken {
            get {
                return ResourceManager.GetString("ServiceUserProcessCookieNoStoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的 Cookie 无法获取用户信息 的本地化字符串。
        /// </summary>
        internal static string ServiceUserProcessCookieRequestUserInfoFailed {
            get {
                return ResourceManager.GetString("ServiceUserProcessCookieRequestUserInfoFailed", resourceCulture);
            }
        }
    }
}
