// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Snap.Hutao.Migrations
{
    public partial class RenameGachaTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_GachaItems_GachaArchives_ArchiveId",
                table: "GachaItems");

            migrationBuilder.DropPrimaryKey(
                name: "PK_GachaItems",
                table: "GachaItems");

            migrationBuilder.DropPrimaryKey(
                name: "PK_GachaArchives",
                table: "GachaArchives");

            migrationBuilder.RenameTable(
                name: "GachaItems",
                newName: "gacha_items");

            migrationBuilder.RenameTable(
                name: "GachaArchives",
                newName: "gacha_archives");

            migrationBuilder.RenameIndex(
                name: "IX_GachaItems_ArchiveId",
                table: "gacha_items",
                newName: "IX_gacha_items_ArchiveId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_gacha_items",
                table: "gacha_items",
                column: "InnerId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_gacha_archives",
                table: "gacha_archives",
                column: "InnerId");

            migrationBuilder.AddForeignKey(
                name: "FK_gacha_items_gacha_archives_ArchiveId",
                table: "gacha_items",
                column: "ArchiveId",
                principalTable: "gacha_archives",
                principalColumn: "InnerId",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_gacha_items_gacha_archives_ArchiveId",
                table: "gacha_items");

            migrationBuilder.DropPrimaryKey(
                name: "PK_gacha_items",
                table: "gacha_items");

            migrationBuilder.DropPrimaryKey(
                name: "PK_gacha_archives",
                table: "gacha_archives");

            migrationBuilder.RenameTable(
                name: "gacha_items",
                newName: "GachaItems");

            migrationBuilder.RenameTable(
                name: "gacha_archives",
                newName: "GachaArchives");

            migrationBuilder.RenameIndex(
                name: "IX_gacha_items_ArchiveId",
                table: "GachaItems",
                newName: "IX_GachaItems_ArchiveId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_GachaItems",
                table: "GachaItems",
                column: "InnerId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_GachaArchives",
                table: "GachaArchives",
                column: "InnerId");

            migrationBuilder.AddForeignKey(
                name: "FK_GachaItems_GachaArchives_ArchiveId",
                table: "GachaItems",
                column: "ArchiveId",
                principalTable: "GachaArchives",
                principalColumn: "InnerId",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
