// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Snap.Hutao.Migrations
{
    /// <inheritdoc />
    public partial class Cultivation : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "cultivate_projects",
                columns: table => new
                {
                    InnerId = table.Column<Guid>(type: "TEXT", nullable: false),
                    IsSelected = table.Column<bool>(type: "INTEGER", nullable: false),
                    Name = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_cultivate_projects", x => x.InnerId);
                });

            migrationBuilder.CreateTable(
                name: "cultivate_entries",
                columns: table => new
                {
                    InnerId = table.Column<Guid>(type: "TEXT", nullable: false),
                    ProjectId = table.Column<Guid>(type: "TEXT", nullable: false),
                    Type = table.Column<int>(type: "INTEGER", nullable: false),
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_cultivate_entries", x => x.InnerId);
                    table.ForeignKey(
                        name: "FK_cultivate_entries_cultivate_projects_ProjectId",
                        column: x => x.ProjectId,
                        principalTable: "cultivate_projects",
                        principalColumn: "InnerId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "cultivate_items",
                columns: table => new
                {
                    InnerId = table.Column<Guid>(type: "TEXT", nullable: false),
                    EntryId = table.Column<Guid>(type: "TEXT", nullable: false),
                    ItemId = table.Column<int>(type: "INTEGER", nullable: false),
                    Count = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_cultivate_items", x => x.InnerId);
                    table.ForeignKey(
                        name: "FK_cultivate_items_cultivate_entries_EntryId",
                        column: x => x.EntryId,
                        principalTable: "cultivate_entries",
                        principalColumn: "InnerId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_cultivate_entries_ProjectId",
                table: "cultivate_entries",
                column: "ProjectId");

            migrationBuilder.CreateIndex(
                name: "IX_cultivate_items_EntryId",
                table: "cultivate_items",
                column: "EntryId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "cultivate_items");

            migrationBuilder.DropTable(
                name: "cultivate_entries");

            migrationBuilder.DropTable(
                name: "cultivate_projects");
        }
    }
}
