// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Snap.Hutao.Migrations
{
    /// <inheritdoc />
    public partial class AddCultivateEntryLevelInformation : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "cultivate_entry_level_informations",
                columns: table => new
                {
                    InnerId = table.Column<Guid>(type: "TEXT", nullable: false),
                    EntryId = table.Column<Guid>(type: "TEXT", nullable: false),
                    AvatarLevelFrom = table.Column<uint>(type: "INTEGER", nullable: false),
                    AvatarLevelTo = table.Column<uint>(type: "INTEGER", nullable: false),
                    SkillALevelFrom = table.Column<uint>(type: "INTEGER", nullable: false),
                    SkillALevelTo = table.Column<uint>(type: "INTEGER", nullable: false),
                    SkillELevelFrom = table.Column<uint>(type: "INTEGER", nullable: false),
                    SkillELevelTo = table.Column<uint>(type: "INTEGER", nullable: false),
                    SkillQLevelFrom = table.Column<uint>(type: "INTEGER", nullable: false),
                    SkillQLevelTo = table.Column<uint>(type: "INTEGER", nullable: false),
                    WeaponLevelFrom = table.Column<uint>(type: "INTEGER", nullable: false),
                    WeaponLevelTo = table.Column<uint>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_cultivate_entry_level_informations", x => x.InnerId);
                    table.ForeignKey(
                        name: "FK_cultivate_entry_level_informations_cultivate_entries_EntryId",
                        column: x => x.EntryId,
                        principalTable: "cultivate_entries",
                        principalColumn: "InnerId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_cultivate_entry_level_informations_EntryId",
                table: "cultivate_entry_level_informations",
                column: "EntryId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "cultivate_entry_level_informations");
        }
    }
}
