// <auto-generated />
// But modified to split rename operation into drop and add.
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Snap.Hutao.Migrations
{
    /// <inheritdoc />
    public partial class NewCharacterDetail : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AttachedUid",
                table: "cultivate_projects");

            migrationBuilder.DropColumn(
                name: "CalculatorRefreshTime",
                table: "avatar_infos");

            migrationBuilder.DropColumn(
                name: "GameRecordRefreshTime",
                table: "avatar_infos");

            migrationBuilder.DropColumn(
                name: "ShowcaseRefreshTime",
                table: "avatar_infos");

            migrationBuilder.DropColumn(
                name: "Info",
                table: "avatar_infos");

            migrationBuilder.AddColumn<string>(
                name: "Info2",
                table: "avatar_infos",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "RefreshTime",
                table: "avatar_infos",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "RefreshTime",
                table: "avatar_infos");

            migrationBuilder.DropColumn(
                name: "Info2",
                table: "avatar_infos");

            migrationBuilder.AddColumn<string>(
                name: "Info",
                table: "avatar_infos",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "AttachedUid",
                table: "cultivate_projects",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "ShowcaseRefreshTime",
                table: "avatar_infos",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "CalculatorRefreshTime",
                table: "avatar_infos",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "GameRecordRefreshTime",
                table: "avatar_infos",
                type: "TEXT",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
        }
    }
}
