// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Snap.Hutao.Service;

#nullable disable

namespace Snap.Hutao.Migrations
{
    /// <inheritdoc />
    public partial class AddCultivationProjectServerTimeZoneOffset : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<TimeSpan>(
                name: "ServerTimeZoneOffset",
                table: "cultivate_projects",
                type: "TEXT",
                nullable: false,
                defaultValue: new TimeSpan(0, 8, 0, 0, 0));

            migrationBuilder.Sql(@"UPDATE `cultivate_projects` 
                                   SET `ServerTimeZoneOffset` = (
                                       SELECT IFNULL(
                                           (SELECT `Value` 
                                            FROM `settings` 
                                            WHERE `Key` = 'CalendarServerTimeZoneOffset'), 
                                           '08:00:00'
                                       )
                                   )");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ServerTimeZoneOffset",
                table: "cultivate_projects");
        }
    }
}