// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Snap.Hutao.Service;

#nullable disable

namespace Snap.Hutao.Migrations
{
    /// <inheritdoc />
    public partial class AddCultivationProjectServerTimeZoneOffset : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<TimeSpan>(
                name: "ServerTimeZoneOffset",
                table: "cultivate_projects",
                type: "TEXT",
                nullable: false,
                defaultValue: new TimeSpan(0, 0, 0, 0, 0));

            // TODO: need evaluation
            TimeSpan defaultServerTimeZoneOffset = Ioc.Default.GetRequiredService<AppOptions>().CalendarServerTimeZoneOffset;
            migrationBuilder.Sql($"UPDATE cultivate_projects SET ServerTimeZoneOffset = '{defaultServerTimeZoneOffset}'");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ServerTimeZoneOffset",
                table: "cultivate_projects");
        }
    }
}